### ISSUE TITLE
Change SQL to NoSQL

### ISSUE THREAD

**Issue by lerenn** [lerenn/cryptellation#110]
There is no relationships in the database and the migrations are a pain.
This would leverage the lazy migration.

**Comment by gedw99** [comment]
Hey @lerenn 

there is a nice sqlite system that does CRSDT multi master sync and subscriptions that I am using with NATS.

https://github.com/superfly/corrosion

It might be your cup of tea.

The big deal is that all instances sync without clashes, because its using a basic CRDT approach.

I managed to get it running and the subscription can feed into NATS easily because its a simple HTTP API.

https://superfly.github.io/corrosion/api/subscriptions.html

Check out the way the change feed works.
